@startuml Booking Interview (DELETE ONE)

header Sample Interview Booking
footer Page %page% of %lastpage%
title "Manage Interview (DELETE ONE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:interviews" as routerInterview
participant "<<controllers>>\n:interviews" as controllersInterviews
participant "<<model>>\n:Interview" as modelInterview
database "<<MongoDB>>\n:interviews" as InterviewDatabase

client->server ++: req.delete('/api/interviews/:id')
server->routerInterview ++: app.use('/api/interviews', interviewsRouter);
routerInterview -> controllersInterviews ++: deleteInterview(req, res, next)
' find interview by id
controllersInterviews->modelInterview ++: findById(req.params.id)
modelInterview -> InterviewDatabase ++: query
InterviewDatabase -> modelInterview --: interview
modelInterview --> controllersInterviews --: interview
' verify interview permission to delete interview
' case 1: req.user.role == 'admin'
' case 2: req.user.id == interview.user && req.user.role != 'admin'
controllersInterviews --> modelInterview ++: if (req.user.role == 'admin')
controllersInterviews --> modelInterview : if (req.user.id == interview.user && req.user.role !== 'admin')
modelInterview -> InterviewDatabase ++: interview.remove()
InterviewDatabase --> modelInterview --: result
modelInterview --> controllersInterviews --: result
controllersInterviews --> client --:     res.status(200).json({ success: true, message: `Interview ${req.params.id} deleted`});
@enduml
