@startuml Booking Interview (GET ONE)

header Sample Interview Booking
footer Page %page% of %lastpage%
title "Manage Interview (GET ONE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:interviews" as routerInterview
participant "<<controllers>>\n:interviews" as controllersInterviews
participant "<<model>>\n:Interview" as modelInterview
database "<<MongoDB>>\n:interviews" as InterviewDatabase

client->server ++: req.get('/api/interviews/:id')
server->routerInterview ++: app.use('/api/interviews', interviews);
routerInterview -> controllersInterviews ++: getInterview(req, res, next)
controllersInterviews->modelInterview ++: findById(req.params.id)
modelInterview -> InterviewDatabase ++: InterviewSchema
InterviewDatabase --> modelInterview --: interview
controllersInterviews <-- modelInterview --: interview
controllersInterviews->client --: res.status(200).json({success: true, data: interview})

@enduml
