@startuml Edit Interview (PUT ONE)

header Sample Interview Booking
footer Page %page% of %lastpage%
title "Edit Interview"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:interviews" as routerInterview
participant "<<controllers>>\n:interviews" as controllersInterviews
participant "<<model>>\n:Interview" as modelInterview
database "<<MongoDB>>\n:interviews" as InterviewDatabase

client->server ++: req.patch('/api/interviews/:id')
server->routerInterview ++: app.use('/api/interviews', interviewsRouter);
routerInterview -> controllersInterviews ++: editInterview(req, res, next)

controllersInterviews->modelInterview ++: Interviews.findByIdAndUpdate(req.params.id, req.body)
modelInterview->InterviewDatabase ++: updateQuery
InterviewDatabase-->modelInterview --: updatedInterview
modelInterview-->controllersInterviews --: updatedInterview
controllersInterviews-->client --: res.status(200).json({ success: true, data: updatedInterview });

@enduml
