@startuml Post One Company

header Companies Management
footer Page %page% of %lastpage%
title "Create Company"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:companies" as routerCompanies
participant "<<controllers>>\n:companies" as controllersCompanies
participant "<<model>>\n:Company" as modelCompany
database "<<MongoDB>>\n:companies" as CompanyDatabase

client->server ++: req.post('/api/companies')
server->routerCompanies ++: app.use('/api/companies', companiesRouter);
routerCompanies -> controllersCompanies ++: createCompany(req, res, next)
controllersCompanies->modelCompany ++: Company.create(req.body)
modelCompany->CompanyDatabase ++: insert
CompanyDatabase-->modelCompany --: company
modelCompany-->controllersCompanies --: company
controllersCompanies-->client --: res.status(201).json({ success: true, data: company });

@enduml
