@startuml Update One Company

header Companies Management
footer Page %page% of %lastpage%
title "Update Company"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:companies" as routerCompanies
participant "<<controllers>>\n:companies" as controllersCompanies
participant "<<model>>\n:Company" as modelCompany
database "<<MongoDB>>\n:companies" as CompanyDatabase

client->server ++: req.put('/api/companies/:id')
server->routerCompanies ++: app.use('/api/companies', companiesRouter);
routerCompanies -> controllersCompanies ++: updateCompany(req, res, next)
controllersCompanies->modelCompany ++: Company.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true })
modelCompany->CompanyDatabase ++: update
CompanyDatabase-->modelCompany --: updatedCompany
modelCompany-->controllersCompanies --: updatedCompany
controllersCompanies-->client --: res.status(200).json({ success: true, data: updatedCompany });
@enduml