@startuml Register User

header Authentication Process
footer Page %page% of %lastpage%
title "User Registration"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<controllers>>\n:authController" as authController
participant "<<model>>\n:User" as userModel
database "<<MongoDB>>\n:users" as UserDatabase

client->server ++: req.post('/api/auth/register')
server->authController ++: register(req, res, next)
authController->userModel ++: User.create(req.body)
userModel->UserDatabase ++: insertUser
UserDatabase-->userModel --: user
userModel-->authController --: sendTokenResponse(user, 200, res)
authController-->client --: res.status(200).cookie(...).json({ success: true, token })

@enduml
