name: Build and Push Docker image

on:
  push:
    branches:
      - main  # Or any branch you want to trigger this action

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Updated to the latest version
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Ensure compatibility with the build-push-action

    - name: Build and push Docker image
      uses: docker/build-push-action@v3  # Updated to the latest version
      with:
        push: true
        tags: weerawatw/cedt-jobfair:latest  # Replace with your Docker Hub username/repository
